json.id plan.id
json.plan_id plan.plan_id
json.price_id plan.price_id
json.name plan.name
json.product_id plan.product_id
json.amount plan.amount
json.currency plan.currency
json.interval plan.interval
json.subscriber_count plan.subscriber_count